#!/bin/sh

set -e

git push origin master $@

GIT_DIR=$(git rev-parse --git-dir)
if [[ $(basename $GIT_DIR) != ".git" ]]; then
	cmessage=$(git log -1 --pretty=%B)

	TOP_LEVEL=$(git rev-parse --show-toplevel)

	cd $TOP_LEVEL/../

	unset GIT_DIR

	PAR_TOP_LEVEL=$(git rev-parse --show-toplevel)
	echo
	basename $PAR_TOP_LEVEL
	submodule="${TOP_LEVEL#$PAR_TOP_LEVEL/}"
	
	status=$(git submodule status $submodule | awk -F '[+ ]' '{print $3 " " $2}')
	git add $submodule

	set +e
	git commit -m "$cmessage" -m "$status"
	set -e

	git spush $@
fi
